export const typeImages: { [key: string]: string } = {
  normal: '../../public/images/normal.png',
  fire: '../../public/images/fogo.png',
  water: '../../public/images/agua.png',
  electric: '../../public/images/eletrico.png',
  grass: '../../public/images/planta.png',
  ice: '../../public/images/gelo.png',
  fighting: '../../public/images/lutador.png',
  poison: '../../public/images/venenoso.png',
  ground: '../../public/images/terrestre.png',
  flying: '../../public/images/voador.png',
  psychic: '../../public/images/psiquico.png',
  bug: '../../public/images/inseto.png',
  rock: '../../public/images/pedra.png',
  ghost: '../../public/images/fantasma.png',
  dragon: '../../public/images/dragao.png',
  dark: '../../public/images/noturno.png',
  steel: '../../public/images/aco.png',
  fairy: '../../public/images/fada.png',
};
